**IRIS DATASET CLASSIFICATION**


In [5]:
import pandas as pd
iris=pd.read_csv("IRIS.csv")

In [6]:
#splitting
from sklearn.model_selection import train_test_split
# Separate features (x) and target (y)
x = iris.iloc[:, :-1]
y = iris.iloc[:, -1]

# Split the data into training and testing sets
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)


In [7]:
########         KNN
from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier(n_neighbors=8)

#fitting
model.fit(x_train,y_train)

#predict
pred=model.predict(x_test)

#Evaluate
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
print(confusion_matrix(y_test,pred))
print(classification_report(y_test,pred))
print(accuracy_score(y_test,pred))


[[12  0  0]
 [ 0 12  1]
 [ 0  1  4]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        12
Iris-versicolor       0.92      0.92      0.92        13
 Iris-virginica       0.80      0.80      0.80         5

       accuracy                           0.93        30
      macro avg       0.91      0.91      0.91        30
   weighted avg       0.93      0.93      0.93        30

0.9333333333333333


In [8]:
##_________SVM
from sklearn.svm import SVC
model=SVC();

#fitting
model.fit(x_train,y_train)

#predict
pred=model.predict(x_test)

#Evaluate
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
print(confusion_matrix(y_test,pred))
print(classification_report(y_test,pred))
print(accuracy_score(y_test,pred))

[[12  0  0]
 [ 0 10  3]
 [ 0  0  5]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        12
Iris-versicolor       1.00      0.77      0.87        13
 Iris-virginica       0.62      1.00      0.77         5

       accuracy                           0.90        30
      macro avg       0.88      0.92      0.88        30
   weighted avg       0.94      0.90      0.91        30

0.9


In [9]:
#DecisionTree
from sklearn.tree import DecisionTreeClassifier
model=DecisionTreeClassifier();

#fitting
model.fit(x_train,y_train)

#predict
pred=model.predict(x_test)

#Evaluate
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
print(confusion_matrix(y_test,pred))
print(classification_report(y_test,pred))
print(accuracy_score(y_test,pred))

[[12  0  0]
 [ 0 10  3]
 [ 0  2  3]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        12
Iris-versicolor       0.83      0.77      0.80        13
 Iris-virginica       0.50      0.60      0.55         5

       accuracy                           0.83        30
      macro avg       0.78      0.79      0.78        30
   weighted avg       0.84      0.83      0.84        30

0.8333333333333334


In [10]:
#Naive Bayes
from sklearn.naive_bayes import MultinomialNB
model=MultinomialNB();

#fitting
model.fit(x_train,y_train)

#predict
pred=model.predict(x_test)

#Evaluate
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
print(confusion_matrix(y_test,pred))
print(classification_report(y_test,pred))
print(accuracy_score(y_test,pred))

[[12  0  0]
 [ 0  0 13]
 [ 0  0  5]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        12
Iris-versicolor       0.00      0.00      0.00        13
 Iris-virginica       0.28      1.00      0.43         5

       accuracy                           0.57        30
      macro avg       0.43      0.67      0.48        30
   weighted avg       0.45      0.57      0.47        30

0.5666666666666667


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


**BREAST CANCER DATASET CLASSIFICATION**


In [11]:
import pandas as pd
import numpy as np
cancer1=pd.read_csv("breast_cancer.csv")

In [12]:
cancer1.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [13]:
cancer1.drop('id',axis=1,inplace=True)
cancer1.drop('Unnamed: 32',axis=1,inplace=True)

In [14]:
cancer1.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [15]:
x=cancer1.drop(['diagnosis'],axis=1)
y=cancer1['diagnosis']

In [16]:
#splitting
from sklearn.model_selection import train_test_split

# Split the data into training and testing sets
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

In [17]:
#____  KNN
from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier(n_neighbors=8)

#fitting
model.fit(x_train,y_train)

#predict
pred=model.predict(x_test)

#Evaluate
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
print(confusion_matrix(y_test,pred))
print(classification_report(y_test,pred))
print(accuracy_score(y_test,pred))


[[72  1]
 [10 31]]
              precision    recall  f1-score   support

           B       0.88      0.99      0.93        73
           M       0.97      0.76      0.85        41

    accuracy                           0.90       114
   macro avg       0.92      0.87      0.89       114
weighted avg       0.91      0.90      0.90       114

0.9035087719298246


In [18]:
##_________SVM
from sklearn.svm import SVC
model=SVC();

#fitting
model.fit(x_train,y_train)

#predict
pred=model.predict(x_test)

#Evaluate
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
print(confusion_matrix(y_test,pred))
print(classification_report(y_test,pred))
print(accuracy_score(y_test,pred))

[[73  0]
 [10 31]]
              precision    recall  f1-score   support

           B       0.88      1.00      0.94        73
           M       1.00      0.76      0.86        41

    accuracy                           0.91       114
   macro avg       0.94      0.88      0.90       114
weighted avg       0.92      0.91      0.91       114

0.9122807017543859


In [19]:
#DecisionTree
from sklearn.tree import DecisionTreeClassifier
model=DecisionTreeClassifier();

#fitting
model.fit(x_train,y_train)

#predict
pred=model.predict(x_test)

#Evaluate
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
print(confusion_matrix(y_test,pred))
print(classification_report(y_test,pred))
print(accuracy_score(y_test,pred))

[[67  6]
 [ 7 34]]
              precision    recall  f1-score   support

           B       0.91      0.92      0.91        73
           M       0.85      0.83      0.84        41

    accuracy                           0.89       114
   macro avg       0.88      0.87      0.88       114
weighted avg       0.89      0.89      0.89       114

0.8859649122807017


In [21]:
#Naive Bayes
from sklearn.naive_bayes import MultinomialNB
model=MultinomialNB();

#fitting
model.fit(x_train,y_train)

#predict
pred=model.predict(x_test)

#Evaluate
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
print(confusion_matrix(y_test,pred))
print(classification_report(y_test,pred))
print(accuracy_score(y_test,pred))

[[73  0]
 [13 28]]
              precision    recall  f1-score   support

           B       0.85      1.00      0.92        73
           M       1.00      0.68      0.81        41

    accuracy                           0.89       114
   macro avg       0.92      0.84      0.86       114
weighted avg       0.90      0.89      0.88       114

0.8859649122807017
